### ISSUE TITLE
Mixed Content errors when loading respack list

### ISSUE THREAD

**Issue by Binary-Wolfeh** [mon/0x40-web#12]
> Mixed Content: The page at 'https://bng.pw/hues/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://cdn.0x40hu.es/getRespacks.php'. This request has been blocked; the content must be served over HTTPS. 

Message appears on both:
- Google Chrome 48.0.2564.116 m
- Mozilla Firefox 42.0

Error message gets thrown when trying to load up the respack list. Would love to submit a pull request instead, but the CDN seems https-incapable.

My alternative solution of falling back to http doesn't work either - i just get redirected back to https version.

**Comment by mon** [comment]
The CDN had a broken SSL config. Contacted AMM and this should be fixed.

**Comment by mon** [comment]
Actually, the cdn still returns http urls in the response so probably still fails. It will be patched but I'll reopen this until it's fixed.

**Comment by Binary-Wolfeh** [comment]
Yup, the issue still persists on my end too. Thank you for the quick reply. :smile:

**Comment by mon** [comment]
CDN has been fixed
